config/routes.rb
Foursweep::Application.routes.draw do
  match "(*any)",
    to: redirect(subdomain: ""),
    via: :all,
    constraints: { subdomain: "www" }

  match "changes" => 'changelog#changes', via: [:get, :post]

  match "stats/" => 'stats#stats', via: [:get, :post]

  match "stats/:user_id" => 'stats#stats', via: [:get, :post]
  match "category_changes" => 'stats#category_changes', via: [:get, :post]

  match "about" => 'static_pages#about', via: [:get, :post]
  match "about/faq" => 'static_pages#faq', via: [:get, :post]
  match "about/changelog" => 'static_pages#changelog', via: [:get, :post]
  match "about/contact" => 'static_pages#contact', via: [:get, :post]
  match "about/suggestion" => 'static_pages#suggestion', via: [:get, :post]

  match 'heartbeat' => 'heartbeat#heartbeat', via: [:get, :post]
  get "flags/list"
  get "flags/check"
  get "flags/newcount"
  match "flags/statuses", via: [:get, :post]
  match 'flags/run' => 'flags#run', :via=>:post
  match 'flags/resubmit' => 'flags#resubmit', :via=>:post
  match 'flags/hide' => 'flags#hide', :via=>:post
  match 'flags/check' => 'flags#check', via: [:get, :post]
  match 'flags/cancel' => 'flags#cancel', via: [:get, :post]

  get "explorer/explore"

  get "session/callback"
  get "session/error"
  get "session/new"
  get "session/logout"
  get "session/not_allowed"

  resources :flags

  root :to => 'explorer#explore'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--[if lt IE 9]>
  <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <title>4sweep</title>
  <link rel="icon" href="https://foursquare.com/favicon.ico" type="image/x-icon"/>
  <link rel="shortcut icon" href="https://foursquare.com/favicon.ico" type="image/x-icon"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-72.png" sizes="72x72"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-76.png" sizes="76x76"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-120.png" sizes="120x120"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-144.png" sizes="144x144"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-152.png" sizes="152x152"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-167.png" sizes="167x167"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-180.png" sizes="180x180"/>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield(:javascripts) %>

  <%= csrf_meta_tags %>
</head>
<body class='<%= yield(:bodyclasses) %>'>
  <div id="wrap">
  <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <ul class="nav">

          <a class="brand" href="/" title="4sweep Home">4sweep</a>
          <li class="divider-vertical"></li>

          <% if @current_user %>
          <li><%= link_to "Explore", root_path %></li>

          <li><a href="<%=flags_path%>">Flags<span id='flagcount'><%= yield(:flagcount) %></span></a></li>
          <% end %>
        </ul>
        <ul class="nav pull-right">
          <% if @current_user %>
          <li class="divider-vertical"></li>
          <li><%= link_to "Category History", category_changes_path %></li>
          <li><%= link_to "Your Stats", stats_path %></li>
          <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown">About</a>
            <ul class="dropdown-menu">
              <li><%= link_to "FAQ", about_faq_path %></li>
              <li><%= link_to "Make a Suggestion", about_suggestion_path %></li>
              <li><%= link_to "Change Log", about_changelog_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Contact", about_contact_path %></li>
            </ul>
          </li>

          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a href="#" class='dropdown-toggle' data-toggle='dropdown'>
              <%= @current_user.foursquare_user['firstName'] %>
              <% if @current_user.level && @current_user.level != '' %>
              (SU<%= @current_user.level %>)
              <% end %>
              <img src="<%=@current_user.photo_src %>" height='25' width='25' alt="">
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Sign out", session_logout_path %></li>
            </ul>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>


  <div class="container-fluid">
    <%= yield %>
  </div>

  </div>
  <% if @current_user %>
  <div class="footer navbar navbar-fixed-bottom">

    <span class='releaseinfo pull-left'>4sweep <%= release %> [<%= link_to "What's New", about_changelog_path %>]</span>
    <span id='footermiddle'><%= yield :footer %></span>
    <span class="pull-right">
      <%= number_with_delimiter(total_flags, :delimiter => ',') %> total flags
      <%= yield :pull_footer %>
      <a href='https://foursquare.com'><%= image_tag "poweredByFoursquare_gray.png" %></a>
    </span>
  </div>
  <% end %>
</body>
</html>

app/views/layouts/noheader.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--[if lt IE 9]>
  <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <title>Foursweep</title>
  <link rel="icon" href="https://foursquare.com/favicon.ico" type="image/x-icon"/>
  <link rel="shortcut icon" href="https://foursquare.com/favicon.ico" type="image/x-icon"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-72.png" sizes="72x72"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-76.png" sizes="76x76"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-120.png" sizes="120x120"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-144.png" sizes="144x144"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-152.png" sizes="152x152"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-167.png" sizes="167x167"/>
  <link rel="apple-touch-icon-precomposed" href="https://foursquare.com/img/metaIcons/touch-icon-180.png" sizes="180x180"/>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield(:javascripts) %>

  <%= yield(:csses) %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>